### ISSUE TITLE
fix(a2d): Qwen2/Qwen3 A2D forward breaks on transformers>=4.57 (attention_type vs layer_types)

### ISSUE THREAD

**Issue by nishide-dev** [nishide-dev/unturtle#262]
## Summary

Four tests in `tests/models/test_a2d.py` fail on current stacks (e.g. `transformers==4.57.6`) with:

```
AttributeError: 'Qwen2DecoderLayer' object has no attribute 'attention_type'
```
(same for `Qwen3DecoderLayer`).

## Root cause

Unturtle`s forked `A2DQwen2Model` / `A2DQwen3Model` (`unturtle/models/a2d/modeling_qwen2.py`, `modeling_qwen3.py`) still indexed the prepared mask map with `decoder_layer.attention_type`.

Upstream **Hugging Face `transformers` (~4.57)** changed `Qwen2Model.forward` / `Qwen3Model.forward` to use **`self.config.layer_types[i]`** per layer instead of an attribute on the decoder layer (see `transformers/models/qwen2/modeling_qwen2.py` around the layer loop, and the analogous Qwen3 file).

`Qwen2Config` / `Qwen3Config` now populate `layer_types` in `__post_init__` when unset, so the correct lookup is `causal_mask_mapping[self.config.layer_types[i]]`.

## Why it used to pass

Older `transformers` exposed `attention_type` on decoder layers (or Unturtle was tested against an older pin). After upgrading the training / Studio pin to 4.57.x, the layer class no longer carries that attribute.

## Fix

Align A2D Qwen2/Qwen3 model `forward` with upstream: `enumerate(self.layers)` and `causal_mask_mapping[self.config.layer_types[i]]`.

## Repro

```bash
.venv/bin/pytest tests/models/test_a2d.py::TestA2DQwen2::test_forward_logits_shape -vv
```

(Used to fail before the forward-loop change; passes after.)

**Comment by nishide-dev** [comment]
Fix implemented in PR #263 (align `A2DQwen2Model` / `A2DQwen3Model` with upstream `config.layer_types[i]`).
